# Generated by Django 6.0.6 on 2026-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Chargers', 'Chargers'), ('Back Covers', 'Back Covers')], max_length=100)),
                ('tags', models.JSONField(default=list, help_text='List of tag strings e.g. ["5g", "camera"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'indexes': [models.Index(fields=['category'], name='idx_product_category'), models.Index(fields=['tags'], name='idx_product_tags')],
            },
        ),
    ]
